language: ruby
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - ruby-head
  - jruby-head
env:
  - "RAILS_VERSION=4.2.10"
  - "RAILS_VERSION=5.1.4"
  - "RAILS_VERSION=master"
matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
    - rvm: ruby-head
    - rvm: jruby-head
